export interface Bcustomers {
    id?:number,
    custtitle?: string,
    custpassport?: string,
    custsurname?: string,    
    custfirstname?: string,    
    custothername?: string,
    custmstatus?: string,    
    custgender?: string,    
    custdob?: string,
    custstateorigin?: string,    
    custreligion?: string,    
    custaddress?: string,    
    custemail?: string,
    custphonenumber?: string,    
    custidcard?: string,  
    custidcardnumber?: string,
    custidcardissued?: string,
    custidcardexpiry?: string,
    custnextkinname?: string,    
    custnextkinaddress?: string,    
    customernextkindob?: string,    
    customernextkinrel?: string,   
    customernextkinphone?: string,
    custusername?: string,    
    custpassword?: string,    
    custpasswordconf?: string,
    accepttermsandcond?:string
}